// connect to the previous mysql
spring.application.name=user2
   server.port=8091

   spring.datasource.url=jdbc:mysql://localhost:3308/user2db
   spring.datasource.username=root
   spring.datasource.password=@gaius2127
   spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
  spring.jpa.hibernate.ddl-auto=update
   spring.jpa.show-sql=true